services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
      - backend-venv:/app/.venv
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "5173:5173"

volumes:
  backend-venv:
  frontend-node-modules:
