"""add categories and listings tables

Revision ID: 987f6002da53
Revises: af75d62f8b14
Create Date: 2026-09-16 12:44:05.023629

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "987f6002da53"
down_revision: str | Sequence[str] | None = "af75d62f8b14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("condition", sa.Enum("NEW", "USED", name="listing_condition"), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "RESERVED", "SOLD", name="listing_status"), nullable=False
        ),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_listings_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_listings_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
    )
    # ### end Alembic commands ###

    categories_table = sa.table(
        "categories", sa.column("id", sa.Uuid()), sa.column("name", sa.String())
    )
    op.bulk_insert(
        categories_table,
        [
            {"id": uuid.uuid4(), "name": name}
            for name in (
                "Электроника",
                "Книги и учебные материалы",
                "Мебель",
                "Одежда и обувь",
                "Спорт и отдых",
                "Разное",
            )
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("listings")
    op.drop_table("categories")
    # ### end Alembic commands ###
