"""add listing photos and rename avatar column

Revision ID: a66d1161ee40
Revises: 6e05b3d5d2a2
Create Date: 2026-09-16 13:06:49.721990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a66d1161ee40"
down_revision: str | Sequence[str] | None = "6e05b3d5d2a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listing_photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listings.id"], name=op.f("fk_listing_photos_listing_id_listings")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_photos")),
    )
    op.alter_column("users", "avatar_url", new_column_name="avatar_object_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "avatar_object_key", new_column_name="avatar_url")
    op.drop_table("listing_photos")
    # ### end Alembic commands ###
